from email.mime.text import MIMEText
from typing import Dict

from .smtp_message import SMTPMessage


class MTMMessage(SMTPMessage):
    @classmethod
    def _get_header(cls) -> str:
        return "<h3><center>The following message was sent via Mail-To-Me:</center></h3><br>"

    @classmethod
    def _get_footer(cls) -> str:
        return """<br><br><br>
        <p><i>This message was automatically generated by the Mail-To-Me application.
        <br>
        If you have not set up a submission form to Mail-To-Me or would like to stop future emails,
        please forward this message along with your request to: mailtome@gmail.com.
        <br>
        For more information on Mail-To-Me visit: https://mailtome.herokuapp.com/</i></p>"""

    @classmethod
    def _build_message(cls, message_params: Dict[str, str]):
        # building str message
        message = cls._get_header()

        message += "\n".join(
            [f"<p>{key}: {value}</p>" for key, value in message_params.items()]
        )

        message += cls._get_footer()

        # forming message structure
        msg = MIMEText(message, "html")
        msg["Subject"] = "Mail-To-Me Automated Message"

        return msg.as_string()


print(MTMMessage("ds", "ds", {}))
